const sidebars = {
  tutorialSidebar: [
    // 1️⃣ Intro file first
    {
      type: "doc",
      id: "intro", // ensure docs/intro.md exists
    },
    // 2️⃣ Chapters
    {
      type: "category",
      label: "Chapter 1",
      items: [{ type: "autogenerated", dirName: "chapter-01-introduction/index"}],
    },
    {
      type: "category",
      label: "Chapter 2",
      items: [
        { type: "autogenerated", dirName: "chapter-02-ros2-foundations/index" },
      ],
    },
    {
      type: "category",
      label: "Chapter 3",
      items: [
        { type: "autogenerated", dirName: "chapter-03-gazebo-simulation/index" },
      ],
    },
    {
      type: "category",
      label: "Chapter 4",
      items: [
        {
          type: "autogenerated",
          dirName: "chapter-04-unity-advanced-simulation/index",
        },
      ],
    },
  ],
};

module.exports = sidebars;
